name: gradle-test-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@main
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: gradle test
        run: gradle test